# This is a basic workflow to help you get started with Actions
name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        image-name: [web,poc]
    steps:
      - name: Build Images And Backup
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hangzhou.aliyuncs.com'
          namespaces: 'adotcode'
          repository_name:"phpmyadmin_${{ matrix.image-name }}"
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: 'v1.0'
          docker_file: './${{ matrix.image-name }}/Dockerfile'

      - uses: actions/checkout@v1
      - name: Components Security Scan - container scan
        run: docker build -t xxxxxxxxzhang/${{ matrix.image-name }}:1.0  -f ./${{ matrix.image-name }}/Dockerfile .
      - uses: anchore/scan-action@master
        with:
          image-reference: "xxxxxxxxzhang/${{ matrix.image-name }}:1.0"
          dockerfile-path: "./${{ matrix.image-name }}/Dockerfile"
          include-app-packages: true
          debug: true
      
      - name: Components Security Scan - anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
      - name: Components Security Scan - show vulnerabilities log in human readable format
        run: jq -r '.vulnerabilities[] | "\(.vuln)\t\(.severity)\t\(.package)\t\(.package_name)\t\(.package_version)"' ./anchore-reports/vulnerabilities.json | sort -k2 | grep -v Negligible  
